name: Deploy ON push

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
            echo "Testing CI/CD pipeline"
            echo "Testing CI/CD pipeline 2"